name: tagion_wallet_flutter
version: 0.0.1
description: Tagion Wallet wrapper for Flutter
author: Vlad Pazych
homepage: tagion.org

environment:
  sdk: ">=2.10.1 <3.0.0"

dependencies:
  ffi: ^0.1.3

dev_dependencies:
  test: ^1.15.7
  flutter_test:
    sdk: flutter
