name: Acceptance tests
on:
  workflow_dispatch:
    inputs:
      tarball: 
        description: "tar ball of the logs and build"
        required: true
        type: string

jobs:
  run_acceptance_stage_tests:
    runs-on: phillip
    steps:
      - name: Mount Artifact
        run: | 
          mkdir -p ARTIFACT
          archivemount ${{inputs.tarball}} ARTIFACT
      - name: Testing
        run: echo $(ls ARTIFACT)

      
      - name: Unmount Artifact
        if: failure() || success()
        run: |
          fusermount -u ARTIFACT
      



      

      # Additional steps here

