name: Acceptance tests
on:
  workflow_run:
    workflows: ["Commit Build and Test"]
    branches: [current-commit]
    types:
      - completed

jobs:
  run_acceptance_stage_tests:
    runs-on: self-hosted
    steps:
      - name: Mount Artifact
        run: | 
          mkdir ARTIFACT
          archivemount ../my_balls.tar.gz ARTIFACT
      - name: Testing
        run: echo $(ls ARTIFACT)
      - name: Unmount Artifact
        run: |
          fusermount -u ARTIFACT
      



      

      # Additional steps here

