name: Acceptance tests
on:
  workflow_dispatch:
    inputs:
      tarball: 
        description: "tar ball of the logs and build"
        required: true
        type: string
      stage:
        description: "the stage that the log should be taken from"
        required: true
        type: string
env:
  TARGET: x86_64-linux
  STAGE: acceptance
  ARTIFACT: ARTIFACT
  RETENTION_DAYS_BINS: 3

jobs:
  run_acceptance_stage_tests:
    runs-on: phillip
    steps:
      - name: Copy Artifact to local machine
        run: |
          cp /mnt/shared/${{inputs.stage}}/${{inputs.tarball}} .
          mkdir -p ${{ env.ARTIFACT }}
          tar -xzf ${{inputs.tarball}} -C ${{ env.ARTIFACT }}
        
      - name: Run collider tests
        run: |
          source ${{ env.ARTIFACT }}/build/${{ env.TARGET }}/bin/bddenv.sh
          export DBIN=$PWD/${{ env.ARTIFACT }}/build/${{ env.TARGET }}/bin
          export DLOG=$PWD/${{ env.ARTIFACT }}/logs/${{ env.TARGET }}
          export COLLIDER_ROOT=$PWD/${{ env.ARTIFACT }}/logs/${{ env.TARGET }}/bdd
          export PATH=$DBIN:$PATH
          ./${{ env.ARTIFACT }}/build/${{ env.TARGET }}/bin/collider -r acceptance -j 2 -b ${{ env.ARTIFACT }}/build/${{ env.TARGET}}/bin/testbench

      - name: Create tar ball
        run: tar -czf ${{inputs.tarball}} --exclude='*.o' ${{ env.ARTIFACT }}/* 
        
      - uses: actions/upload-artifact@v3
        if: failure() || success()
        with:
          name: failed-run
          path: ./${{inputs.tarball}}
      
      - name: Upload to shared directory
        if: success()
        run: |
          folder=/mnt/shared/${{env.STAGE}}
          mkdir -p $folder
          cp ${{inputs.tarball}} $folder
        
      - name: Cleanup
        if: success() || failure()
        run: |
          rm ${{ inputs.tarball }}
          rm -rf ${{env.ARTIFACT}}
      



      

      # Additional steps here

