name: android
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${secrets.GITBOT_TOKEN}

jobs:
  commit_stage:
    runs-on: CI-2
    steps:
      - name: get repository
        run: |
          cd ..
          git clone git@github.com:tagion/tagion.git || echo "repo already exists"

      - name: pull
        run: |
          git clean -f && git restore . 
          git checkout current
          git pull

      - name: Install android tools
        run: |
          make -j -f tub/scripts/setup_android_toolchain.mk

      - name: Build
        run: |
          export PATH="tools/ldc2-1.29.0-linux-x86_64/bin:$PATH"
          make DC=ldc2 ANDROID_NDK=tools/android-ndk-r21b/ PLATFORM=aarch64-linux-android libmobile

      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: android-libmobile
          path: ./build/aarch64-linux-android/lib/
          if-no-files-found: error
