name: codecov
on:
  workflow_dispatch:
  push: 
    branches: 
      - current
      - codecov
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
permissions:
  contents: read
  pages: write
  id-token: write      

jobs:
  codecov:
    runs-on: self-hosted
    steps:
      - name: codecov report
        run: |
          pwd
          ls -l
          cd tagion
          pwd
          git pull tagion
          ls -l
          make unittest COV=1
          bash <(curl -s https://codecov.io/bash) -t 80252d60-5311-4a63-8ffe-823decc0cb79
