name: Code Coverage
on:
  workflow_dispatch:
    inputs:
      tarball: 
        description: "tar ball of the logs and build"
        required: true
        type: string
      stage:
        description: "the stage that the log should be taken from"
        required: true
        type: string
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  TARGET: x86_64-linux
  UNITTEST_COV: unittest-cov

permissions:
  contents: read
  pages: write
  id-token: write      

jobs:
  codecov:
    runs-on: old
    steps:
      - name: Copy Artifact to local machine
        run: |
          rm -- *.lst
          rm -rf *
          cp /mnt/shared/${{inputs.stage}}/${{inputs.tarball}} .
          tar -xzf ${{inputs.tarball}}
      - name: codecov report
        run: |
          ls logs/cov
          cd logs/cov
          bash <(curl -s https://codecov.io/bash) -t ${{ env.CODECOV_TOKEN }}
      
      # - name: codecov report
      #   run: |
          
      #     pwd
      #     mkdir -p codecov || echo "codecov dir already exists"
      #     cd codecov
      #     git clone --recurse-submodules -j8 git@github.com:tagion/tagion.git || echo "repo already exists"
      #     cd tagion
      #     git pull 
      #     make unittest COV=1 DC=dmd
      #     bash <(curl -s https://codecov.io/bash) -t ${{ env.CODECOV_TOKEN }}
          
