name: Commit Build and Test
on:
  workflow_dispatch:
  push: 
    branches: 
      - current-commit
env:
  TARGET: x86_64-linux
  STAGE: commit
  DC: dmd
jobs:
  build_and_unittest:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: run tests
        run: make clean test -j
      
      - name: Report unittests
        if: success()
        run: |
          RESULT=$(cat logs/${{ env.TARGET }}/unittest.log | grep -E "^[0-9]+ modules passed unittests")
          echo -e "### :heavy_check_mark: Unittests passed \n $RESULT" >> $GITHUB_STEP_SUMMARY

      -name: Report bddtests
        run: | 
          RESULT=$(./build/${{ env.TARGET }}/bin/collider -c logs/bdd/{{ env.STAGE }}/results)
          echo $RESULT | grep "Test result success!"
          echo -e "\n $RESULT" >> $GITHUB_STEP_SUMMARY
      
      -name: Create passed tag
        if: success() && (github.ref == 'refs/heads/current')
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "passed"
          force_push_tag: true

      -name: Create failed tag
        if: failure() && (github.ref == 'refs/heads/current')
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "failed"
          force_push_tag: true

      -name: Create tar ball
        run: tar -czvf my_balls.tar.gz --exclude='*.o' logs/ build/

      
    
 