name: Commit Build and Test
on:
  workflow_dispatch:
  push: 
    branches: 
      - current
env:
  TARGET: x86_64-linux
  STAGE: commit
  DC: dmd
  PARALLEL: 2
  RETENTION_DAYS_BINS: 3

jobs:
  build_and_test:
    runs-on: CI-1
    steps:
      - name: get repository
        run: git clone git@github.com:tagion/tagion.git || echo "repo already exists"
      - name: pull
        run: |
          pwd
          id
          ls -l
          git checkout current
          git pull
# make it work with recursive submodules
      - name: Add schedule to build
        run: cp schedule.json build/${{ env.TARGET }}/bin
      - name: Run tests
        run: |
          make clean ci -j ${{env.PARALLEL}} DC=${{env.DC}} || make proper ci -j ${{env.PARALLEL}} DC=${{env.DC}}
          
      - name: Report unittests
        run: |
          RESULT=$(cat logs/${{ env.TARGET }}/unittest.log | grep -E "^[0-9]+ modules passed unittests")
          echo -e "### :heavy_check_mark: Unittests passed \n $RESULT" >> $GITHUB_STEP_SUMMARY

      - name: Report bddtests
        run: | 
          RESULT=$(./build/${{ env.TARGET }}/bin/collider -c logs/${{ env.TARGET }}/bdd/${{ env.STAGE }}/results)
          echo $RESULT | grep "Test result success!"
          ./build/${{env.TARGET}}/bin/shittier -o /dev/stdout logs/ >> $GITHUB_STEP_SUMMARY
               
      - name: Create tar ball
        if: success() || failure()
        id: create_tar
        run: |
          commit_hash=$(git rev-parse --short HEAD)
          timestamp=$(date +%M-%H-%d-%m-%y)
          tar_filename="${commit_hash}-${timestamp}.tar.gz"
          mv build/trunk/trunk.tgz $tar_filename
          echo -e "\nRelease candidate is: $tar_filename" >> $GITHUB_STEP_SUMMARY
          echo "tar_filename=$tar_filename" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: failed-run
          path: ./${{steps.create_tar.outputs.tar_filename}}
      
      - name: Upload to shared directory
        if: success()
        run: |
          folder=/mnt/shared/${{env.STAGE}}
          mkdir -p $folder
          cp ${{steps.create_tar.outputs.tar_filename}} $folder
          
      - name: Start next workflow
        if: success()
        run: gh workflow run acceptance.yml -f tarball=${{ steps.create_tar.outputs.tar_filename }} -f stage=${{ env.STAGE }}
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
 
      - name: Cleanup
        if: success() || failure()
        run: rm ${{ steps.create_tar.outputs.tar_filename }}
