name: ddoc
on:
  workflow_dispatch:
  push: 
    branches: 
      - current
      - ddoc-github-pages

jobs:
  ddoc_build:
    deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install packages 
        run: |
          pwd
          ls -l
          whoami
          sudo wget https://netcologne.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
          sudo apt-get update --allow-insecure-repositories
          sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring
          sudo apt-get update -y && sudo apt-get install -y dmd-compiler dub
          sudo apt-get -y install make screen autoconf golang clang libclang-dev libtool
          cd /usr/local/bin
          wget https://github.com/ldc-developers/ldc/releases/download/v1.29.0/ldc2-1.29.0-linux-x86_64.tar.xz
          tar xf ldc2-1.29.0-linux-x86_64.tar.xz
          export PATH="/usr/local/bin/ldc2-1.29.0-linux-x86_64/bin:$PATH"
          wget https://downloads.dlang.org/pre-releases/2.x/2.102.0/dmd.2.102.0-rc.1.linux.tar.xz
          tar xf dmd.2.102.0-rc.1.linux.tar.xz
          export PATH="/usr/local/bin/dmd2/linux/bin64:$PATH"
          wget https://github.com/jacob-carlborg/dstep/releases/download/v1.0.0/dstep-1.0.0-linux-x86_64.tar.xz
          tar xf dstep-1.0.0-linux-x86_64.tar.xz
          sudo rm -rf /usr/bin/go
          cd /usr/bin/
          sudo wget https://go.dev/dl/go1.20.2.linux-amd64.tar.gz
          sudo gunzip go1.20.2.linux-amd64.tar.gz
          sudo tar -xf go1.20.2.linux-amd64.tar
          sudo chmod +x /usr/bin/go/bin/*
          export PATH="/usr/bin/go/bin:$PATH"
          export GOPATH="/usr/bin/go/bin"
          dstep --version # 1.0.0
          ldc2 --version
          dmd --version
          go version
          cd /home/runner/work/tagion/tagion
          npm i docsify-cli -g
          make ddoc
          ls -l build/
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build/ddoc'
      - name: Deploy to GitHub Pages
        id: ddoc_deployment
        uses: actions/deploy-pages@v1
          
          
          
          
