name: ddoc 
on:
  push:
    branches:
      - current
      - ddoc-github-pages
      
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: install packages 
        run:
          sudo wget https://netcologne.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
          sudo apt-get update --allow-insecure-repositories
          sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring
          sudo apt-get update -y && sudo apt-get install -y dmd-compiler dub
          sudo apt-get -y install make screen autoconf golang clang libclang-dev libtool
          pwd 
          ls -l
          id
          


      	