name: Build ddoc
on:
  workflow_dispatch:
    inputs:
      tarball: 
        description: "tar ball of the logs and build"
        required: true
        type: string
      stage:
        description: "the stage that the log should be taken from"
        required: true
        type: string
    
env:
  TARGET: x86_64-linux

permissions:
  contents: read
  pages: write
  id-token: write      

jobs:
  ddoc_build:
    runs-on: old 
    steps:
      - name: Copy Artifact to local machine
        run: |
          rm -rf *
          cp /mnt/shared/${{inputs.stage}}/${{inputs.tarball}} .
          tar -xzf ${{inputs.tarball}}

      - name: Send ddoc to repository 
        run: |
          git clone https://${{ secrets.API_TOKEN_GITHUB }}@github.com/tagion/ddoc.git
          mv build/ddoc ddoc
          cd ddoc
          git config user.email "mm@decard.io"
          git config user.name "Matlab"
          git add .
          git commit -m "ddocs updated" || echo "nothing to commit"
          git push https://${{ secrets.API_TOKEN_GITHUB }}@github.com/tagion/ddoc.git || echo "repo already up to date"

      - name: clean up
        run: rm -rf *
          
