name: Build D code docmentation
on:
  workflow_dispatch:
  workflow_call:

jobs:
  ddoc:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout ddoc
        env: 
          GITHUB_TOKEN: ${{ secrets.GITBOT_TOKEN }}
        run: |
          gh repo clone https://github.com/tagion/ddoc


      - uses: actions/checkout@v4
        with: 
          path: ./tagion

      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest

      - name: Build docmentation
        run: |
          cd tagion
          make ddoc

      - name: update ddoc repo
        env: 
          GITHUB_TOKEN: ${{ secrets.GITBOT_TOKEN }}
        run: |
          cp -r ./tagion/build/ddoc/ ddoc/
          cd ddoc
          git config user.email "gitbot@decard.io"
          git config user.name "gitbot"
          git add .
          git commit -m "ddocs updated" || echo "nothing to commit"
          git push https://tagion-bot:${{ secrets.GITBOT_TOKEN }}@github.com/tagion/ddoc.git master
