name: ddoc
on:
  workflow_dispatch:
  push: 
    branches: 
      - current
      - ddoc-github-pages

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: install packages 
        run: |
          ls -l
          pwd
          id
