name: Makefile CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
      
    - name: unit test
      run:  wget https://github.com/jacob-carlborg/dstep/releases/download/v1.0.0/dstep-1.0.0-linux-x86_64.tar.xz && tar -xvf dstep-1.0.0-linux-x86_64.tar.xz && cp dstep /usr/local/bin && which dstep && which autoconf && which gcc &&
            wget https://github.com/ldc-developers/ldc/releases/download/v1.28.1/ldc2-1.28.1-linux-x86_64.tar.xz && tar -xvf ldc2-1.28.1-linux-x86_64.tar.xz && cp -r ldc2-1.28.1-linux-x86_64/bin/ && which ldc2  
