name: Makefile CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  unit-test:
    runs-on: self-hosted
    steps:
    - name: unittest  
      run: |  
        rm -rf tagion
        git clone --recurse-submodules -j8 git@github.com:tagion/tagion.git
        cd tagion
        export GITHUB_WORKFLOW_BRANCH=$GITHUB_HEAD_REF
        echo $GITHUB_WORKFLOW_BRANCH
        git checkout $GITHUB_WORKFLOW_BRANCH
        git branch
        git submodule update --recursive --init
        make unittest 
        
    - name: unittest result
      run: |
        tail -n 3 /home/runner/work/tagion/tagion/tagion/logs/x86_64-linux/unittest.log | head -n 1 | grep passed
