name: Makefile CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: oleksiyrudenko/gha-git-credentials@v2.1
      with:
        global: true
        name: 'Matlab '
        email: 'matlab.mehdiyev@gmail.com'
        actor: 'Matlab'
        token: '${{ secrets.ACTION_TOKEN }}'
    - name: unit test
      run: |  
        pwd
        wget https://github.com/jacob-carlborg/dstep/releases/download/v1.0.0/dstep-1.0.0-linux-x86_64.tar.xz
        tar -xvf dstep-1.0.0-linux-x86_64.tar.xz 
        cp dstep /usr/local/bin
        wget https://github.com/ldc-developers/ldc/releases/download/v1.28.1/ldc2-1.28.1-linux-x86_64.tar.xz
        tar -xvf ldc2-1.28.1-linux-x86_64.tar.xz
        pwd
        ls -la
        export PATH=$PATH:/home/runner/work/tagion/tagion/ldc2-1.28.1-linux-x86_64/bin
        which dstep
        which ldc2
        which gcc
        which autoconf
        go version
        sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
        git clone git@github.com:tagion/tagion.git
        cd tagion
        git submodule update --recursive --init
        make unittest || make unittest
