name: Makefile CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  unit-test:

    runs-on: self-hosted

    steps:   
    - name: unit test
      run: |  
        pwd
        ls -la
        which dstep
        which ldc2
        which gcc
        which autoconf
        go version
        git@github.com:tagion/tagion.git
        cd tagion
        git submodule update --recursive --init
        make unittest || make unittest
