name: Makefile CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  unit-test:

    runs-on: self-hosted

    steps:   
    - name: unit test
      run: |  
        pwd
        source ~/.bashrc
        whoami
        ls -la
        which dstep
        which ldc2
        which gcc
        which autoconf
        go version
        rm -rf tagion
        git clone --recurse-submodules -j8 git@github.com:tagion/tagion.git
        cd tagion
        git branch
        git submodule update --recursive --init
        make unittest || make unittest
