name: Makefile CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  unit-test:
    runs-on: self-hosted
    steps:   
    - name: unit test
      run: |  
        pwd
        ls -la
        source ~/.bashrc
        which dstep
        which ldc2
        which gcc
        which autoconf
        go version
        rm -rf tagion
        git clone --recurse-submodules git@github.com:tagion/tagion.git
        git branch
        git submodule update --recursive --init
        make unittest || make unittest
        
    - name: unittest result
      run: |
        tail -n 3 /home/runner/work/tagion/tagion/tagion/logs/x86_64-linux/unittest.log | head -n 1 | grep FAILED && exit 1
