name: Makefile CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  unit-test:
    runs-on: self-hosted
    steps:
    - name: unittest  
      run: |
        pwd
        source ~/.bashrc
        which ldc2
        which gdc
        id
        cd tagion
        pwd
        export GITHUB_WORKFLOW_BRANCH=$GITHUB_HEAD_REF
        echo $GITHUB_WORKFLOW_BRANCH
        git checkout $GITHUB_WORKFLOW_BRANCH
        git branch
        make unittest
        
    - name: unittest result
      run: |
        tail -n 5 /home/moonbase/actions-runner/_work/tagion/tagion/tagion/logs/x86_64-linux/unittest.log | head -n 1 | grep passed
        
        
    - name: regression test
      run: |
        make bins 
        cd build/x86_64-linux/bin/
        docker pull tagion/playnet
        docker run --net host -v ${PWD}:/usr/local/bin tagion/playnet tagionwave -h
    
