name: Makefile CI

on:
  pull_request:
    branches: [ "develop" ]
env:
  ## Sets environment variable
  BINS_DIR: /home/moonbase/actions-runner/_work/tagion/tagion/tagion/build/x86_64-linux/bin
  SCRIPTS_DIR: /home/moonbase/actions-runner/_work/tagion/tagion/core-test-scripts

jobs:
  unit-test:
    runs-on: self-hosted
    steps:
    - name: unittest  
      run: |
        pwd
        source ~/.bashrc
        cd tagion
        export GITHUB_WORKFLOW_BRANCH=$GITHUB_HEAD_REF
        echo $GITHUB_WORKFLOW_BRANCH
        git checkout $GITHUB_WORKFLOW_BRANCH
        git branch
        make unittest
        make bins 
        cd build/x86_64-linux/bin/
  
    - name: unittest result
      run: |
        tail -n 5 /home/moonbase/actions-runner/_work/tagion/tagion/tagion/logs/x86_64-linux/unittest.log | head -n 1 | grep passed
        
  regression-test:
    runs-on: self-hosted
    steps:
    - name: npm scenario
      run: |
        pwd
        rm -rf test_scripts/ || ls -l
        git clone git@github.com:holyanytskyy/test_scripts.git
        cat test_scripts/readme.md | grep start | awk '{print $6}' > scenarios.txt
        cat scenarios.txt
        docker rmi npm-scenario-image || docker images
        docker build -t npm-scenario-image .
        for SCENARIO in scenarios.txt; do docker run --name $SCENARIO --rm npm-scenario $SCENARIO ; done
        
