name: Test Tagionwave
on: 
  workflow_dispatch:
    #    inputs:
    #      logLevel:
    #        description: 'Log level'
    #        required: true
    #        default: 'warning'
    #        type: choice
    #        options:
    #          - info
    #          - warning
    #          - debug
    #      print_tags:
    #        description: 'True to print to STDOUT'
    #        required: true
    #        type: boolean
    #      tags:
    #        description: 'Test scenario tags'
    #        required: true
    #        type: string
    #      environment:
    #        description: 'Environment to run tests against'
    #        type: environment
    #        required: true

jobs:
  deploy_tagionwave:
    runs-on: testnet
      environment:
        name: testnet-mobile
        url: 10.210.2.10
    steps:
      - name: get artifact
        run: |
          rm -rf *
          loginctl enable-linger moonbase
          gh run download -n successful_artifact --repo tagion/tagion
          tar -xzf *.tar.gz

      - name: Initialize network bills
        run: |
          echo "hello"

      - name: start service
        run: |
          cd build/x86_64-linux/bin
          export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus
          export XDG_RUNTIME_DIR=/run/user/1001
          systemctl stop --user neuewelle.service | echo "No service was running"
          mkdir -p ~/.local/share/wave
          mkdir -p ~/.config/systemd/user
          cp tagion ~/.local/share/wave
          cp neuewelle.service ~/.config/systemd/user
          systemctl --user daemon-reload
          systemctl restart --user neuewelle.service
